config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'profile'}


  # For details on the DSL available within this file, 
  # see http://guides.rubyonrails.org/routing.html

  root to: 'pages#home'

# except: define exceptions in the ressource routes
  resources :works, except: [:show] 
  get 'work/:id', to: 'works#show', as: 'work_show'

  resources :blogs do 
    #this function toggle status (published / draft) of blog posts (see index.html.erb)
    member do
      get :toggle_status
    end
  end
  

  get 'home', to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

end

app/models/work.rb
class Work < ApplicationRecord
    has_many :technologies
    accepts_nested_attributes_for :technologies,  #no technology is required in the form, we only validate if blank, since added automagically
                                                                  reject_if: lambda { |x|  x['name'].blank? }  
    #because of the previous line, we want nested items for technologies.  
    #Therefore, we can create a new Work item from console using this syntax  :
    # Work.create!(title: "title", subtitle: "subtitle", body: "body", technologies_attributes[{ name: "Ruby"'}, {  name: "Javascript"}, { name: "AngularJS"}, { name: "Ionic" }])

    include Placeholder

    extend FriendlyId
  friendly_id :title, use: :slugged


  #validate work variables
  validates_presence_of :title, :body, :main_image, :thumb_image
  
def self.angular
    where(subtitle: 'Angular')
end


#set default values for images (if empty)
after_initialize :set_defaults

def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '200')
end


end

app/controllers/works_controller.rb
class WorksController < ApplicationController
    before_action :set_work, only: [:show, :edit, :update, :destroy]
layout 'work'

  def index
    @work_items = Work.all
  end

#render the work form
  def new 
    @work_item = Work.new
    #the following is for testing only and will get improved in future version.
    3.times { @work_item.technologies.build } #instanciate 3 types of technologies, and make it available to the form
  end
 
#create the work when form submitted
  def create
    @work = Work.new(work_params)
    
    respond_to do |format|
      if @work.save
        format.html { redirect_to works_path, notice: 'Work item was successfully created!'}
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @work_item = set_work
        3.times { @work_item.technologies.build } #instanciate 3 types of technologies, and make it available to the form

  end


  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    @work_item = set_work

    respond_to do |format|
      if @work_item.update(params.require(:work).permit(:title, :subtitle, :body))
        format.html { redirect_to works_path, notice: 'work was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
     @work_item = set_work
  end



 
  def destroy
    #perform the lookup
    @work_item = set_work
    # destroy the item
    @work_item.destroy
    # redirect to another url
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'The work record was successfully removed.' }
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:title, :subtitle, :body, technologies_attributes: [:name])
    end


end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_form.html.erb
<%= form_for(@work_item) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :work_title %>
  </div>

<div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle, id: :work_subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :work_body %>
  </div>


  <ul>
    <%= form.fields_for :technologies do  |x| %>
      <li><%= x.label :name %></li>
      <li><%= x.text_field :name %></li>
    <% end %>
 </ul>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/works/_work_item.html.erb
    <% cache do %>


    <p><%= link_to work_item.title, work_show_path(work_item) %></p>
    <p><%= work_item.subtitle %></p>
    <p><%= work_item.body %></p>
        <%= image_tag work_item.thumb_image unless work_item.thumb_image.nil? %>
    <p><%= link_to "Edit", edit_work_path(work_item.id) %></p>

    <p><%= link_to 'Delete portfolio item', work_path(work_item), method: :delete, data: { confirm: 'Are you sure?  This action cannot be reverted.' } %></p>

<hr>
    <% end %>

app/views/works/_work_ruler.html.erb
<hr />

app/views/works/edit.html.erb
<h1>Edit this portfolio item</h1>
<%= render 'form', work_item: @work_item  %>

app/views/works/index.html.erb
<h1>Demo Work Items</h1>
<%=  link_to "Create new item", new_work_path %>
    <%= render partial: 'work_item', collection: @work_items, spacer_template: 'work_ruler' %>

app/views/works/new.html.erb
<h1>Create a new demo work item</h1>
<%= render 'form', work_item: @work_item  %>

app/views/works/show.html.erb
<%= image_tag @work_item.main_image unless @work_item.main_image.nil? %>


    <h1>
        <%= @work_item.title %>
    </h1>

    <em><%= @work_item.subtitle %></em>

    <article>
        <%= @work_item.body %>
    </article>

    <h2>Technologies used : </h2>
    <% @work_item.technologies.each do |t| %>
    <p><%= t.name %> </p>
    <% end %>
    <hr>